; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:latest_stable]
platform = native
lib_deps = 
	Unity
	./
build_flags = 
	-std=c23
	-Wall
	-Wextra
	-Wpedantic
	-Werror
	-DEAGLETRT_STATIC=
	-DEAGLETRT_STATIC_INLINE=
